- hosts: localhost
  tasks:
    - name: Disable Dynamic Workspaces in GNOME Shell
      dconf:
        key: /org/gnome/shell/overrides/dynamic-workspaces
        value: "false"
    - name: Configure Git
      community.general.git_config:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        scope: global
      loop:
        - { name: user.name, value: "David Strauss" }
        - { name: user.email, value: "david@davidstrauss.net" }
        - { name: init.defaultBranch, value: "main" }
        - { name: color.ui, value: "auto" }
