- hosts: localhost
  gather_facts: false
  tasks:
    - name: Install File Roller Archive Manager
      flatpak:
        name: org.gnome.FileRoller
    - name: Install Baobab File Usage Analyzer
      flatpak:
        name: org.gnome.baobab
    - name: Install Builder
      flatpak:
        name: org.gnome.Builder
    - name: Install Junction
      flatpak:
        name: re.sonny.Junction
    - name: Install Steam
      flatpak:
        name: com.valvesoftware.Steam
    - name: Install Camera Controls
      flatpak:
        name: hu.irl.cameractrls
    - name: Install the GIMP
      flatpak:
        name: org.gimp.GIMP
    - name: Install Inkscape
      flatpak:
        name: org.inkscape.Inkscape
    - name: Install Meld
      flatpak:
        name: org.gnome.meld
    - name: Install Fragments
      flatpak:
        name: de.haeckerfelix.Fragments
    - name: Install GHex Editor
      flatpak:
        name: org.gnome.GHex
    - name: Install Dconf Editor
      flatpak:
        name: ca.desrt.dconf-editor
    - name: Install GNU Octave
      flatpak:
        name: org.octave.Octave
    - name: Install LibreOffice
      flatpak:
        name: org.libreoffice.LibreOffice
    - name: Install Fedora Media Writer
      flatpak:
        name: org.fedoraproject.MediaWriter
    - name: Install Parabolic
      flatpak:
        name: org.nickvision.tubeconverter
    - name: Disable DConf Editor Warning
      dconf:
        key: /ca/desrt/dconf-editor/show-warning
        value: "false"
    - name: Interpret Caps Lock as Ctrl
      dconf:
        key: /org/gnome/desktop/input-sources/xkb-options
        value: "['caps:ctrl_modifier']"
    - name: Automatically Remove Old Temporary Files
      dconf:
        key: /org/gnome/desktop/privacy/remove-old-temp-files
        value: "true"
    - name: Automatically Remove Old Trash Files
      dconf:
        key: /org/gnome/desktop/privacy/remove-old-trash-files
        value: "true"
    - name: Assume GNOME Software Has Been Used Before
      dconf:
        key: /org/gnome/software/first-run
        value: "false"
    - name: Disable Donation Reminder
      dconf:
        key: /org/gnome/settings-daemon/plugins/housekeeping/donation-reminder-enabled
        value: "false"
    - name: Use 24-Hour Clock Format
      dconf:
        key: /org/gnome/desktop/interface/clock-format
        value: "'24h'"
    - name: Show Seconds on the Desktop Clock
      dconf:
        key: /org/gnome/desktop/interface/clock-show-seconds
        value: "true"
    - name: Show Weekday on the Desktop Clock
      dconf:
        key: /org/gnome/desktop/interface/clock-show-weekday
        value: "true"
    - name: Use Natural Scrolling
      dconf:
        key: /org/gnome/desktop/peripherals/mouse/natural-scroll
        value: "true"
    - name: Use Static Workspaces
      dconf:
        key: /org/gnome/mutter/dynamic-workspaces
        value: "false"
    - name: Use a Single Workspace
      dconf:
        key: /org/gnome/desktop/wm/preferences/num-workspaces
        value: "1"
    - name: Use List View in Nautilus
      dconf:
        key: /org/gnome/nautilus/preferences/default-folder-viewer
        value: "'list-view'"
    - name: Allow Volume Above 100%
      dconf:
        key: /org/gnome/desktop/sound/allow-volume-above-100-percent
        value: "true"
    - name: Disable Sleep on AC Power
      dconf:
        key: /org/gnome/settings-daemon/plugins/power/sleep-inactive-ac-type
        value: "'nothing'"
    - name: Disable All GNOME Extensions
      dconf:
        key: /org/gnome/shell/enabled-extensions
        value: "@as []"
    - name: Configure F12 to Reset and Clear the Terminal
      dconf:
        key: /org/gnome/terminal/legacy/keybindings/reset-and-clear
        value: "'F12'"
    - name: Read Default Terminal Profile
      shell: "gsettings get org.gnome.Terminal.ProfilesList default | tr --delete \"'\""
      register: terminal_default_profile
      changed_when: false
    - name: Add ~/Projects to GNOME Search Locations
      dconf:
        key: /org/freedesktop/tracker/miner/files/index-recursive-directories
        value: "['&DOCUMENTS', '&MUSIC', '&PICTURES', '&VIDEOS', '/home/{{ ansible_user_id }}/Projects']"
    - name: Terminal - Unlimited Scrollback
      dconf:
        key: /org/gnome/terminal/legacy/profiles:/:{{ terminal_default_profile.stdout }}/scrollback-unlimited
        value: "true"
      when: not ansible_check_mode
    - name: Read Default Ptyxis Profile
      shell: "dconf read /org/gnome/Ptyxis/default-profile-uuid | tr --delete \"'\""
      register: ptyxis_default_profile
      changed_when: false
    - name: Ptyxis - Configure F12 to Reset and Clear
      dconf:
        key: /org/gnome/Ptyxis/Shortcuts/reset-and-clear
        value: "'F12'"
    - name: Ptyxis - Unlimited Scrollback
      dconf:
        key: /org/gnome/Ptyxis/Profiles/{{ ptyxis_default_profile.stdout }}/limit-scrollback
        value: "false"
      when: not ansible_check_mode
